const chatter = [
    {condition: "general", value: "Soft tyres will give you more grip in dry and hot conditions."},
    {condition: "general", value: "Medium tyres offer a small speed boost with no loss in grip."},
    {condition: "general", value: "Hard tyres deliver the best top speed but at the expense of grip."},
    {condition: "general", value: "Tyre bonuses apply to tyre stats only."},
    {condition: "general", value: "Matching tyres with weather will multiply tyre stats."},
    {condition: "general", value: "Picking the wrong tyres will result in weather penalties."},

    {condition: "dry", value: "Soft tyres enhance grip."},
    {condition: "dry", value: "Hard tyres boost top speed."},
    {condition: "dry", value: "Medium tyres are a smart choice."},

    {condition: "hot", value: "Soft tyres will deliver a lot of extra grip in hot conditions."},
    {condition: "hot", value: "Medium tyres offer some extra grip in hot conditions."},
    {condition: "hot", value: "Hard tyres will gain some extra grip in hot weather."},

    {condition: "lightrain", value: "Intermediate tyres are the best solution for light rain."},
    {condition: "lightrain", value: "Light rain conditions call for intermediate tyres."},
    {condition: "lightrain", value: "Just a bit of rain today, but intermediate tyres will do wonders."},
    {condition: "lightrain", value: "In light rain conditions it's best to equip some intermediate tyres."},
    {condition: "lightrain", value: "Non-wet tyres have very low performance in wet conditions."},
    {condition: "lightrain", value: "Intermediate tyres perform better than wet tyres in light rain conditions."},

    {condition: "heavyrain", value: "Wet weather tyres are best at cutting through deep water."},
    {condition: "heavyrain", value: "In heavy rain, wet tyres are the best choice."},
    {condition: "heavyrain", value: "When it's raining this much it's wise to equip wet tyres."},
    {condition: "heavyrain", value: "The circuit is really bogged with water today, wet tyres are key."},
    {condition: "heavyrain", value: "Non-wet tyres have very low performance in wet conditions."},
    {condition: "heavyrain", value: "Wet tyres perform better than intermediate tyres in very wet conditions."},

    {condition: "australia", value: "Albert Park is a very fast circuit."},
    {condition: "australia", value: "Acceleration is key for taking corners well."},
    {condition: "australia", value: "Drivers will need to focus more than anything."},
    {condition: "australia", value: "Concentration is vital if drivers are to excel here in Australia."},
    {condition: "australia", value: "Downforce won't be the first concern for Albert Park."},
    {condition: "australia", value: "Teams will want to build for speed in Australia."},

    {condition: "bahrain", value: "Bahrain is a difficult circuit with very tight corners."},
    {condition: "bahrain", value: "Teams will need to pay attention to downforce to make these corners."},
    {condition: "bahrain", value: "Lots of room for maneuver here, relentless drivers will be rewarded."},
    {condition: "bahrain", value: "Bahrain certainly demands drivers be switched on."},
    {condition: "bahrain", value: "This circuit won't put too much stress on driver endurance."},
    {condition: "bahrain", value: "Drivers should be looking to give their all in Bahrain."},
    {condition: "bahrain", value: "Bahrain is not the fastest circuit, but it's not slow either."},

    {condition: "china", value: "The Shanghai circuit features some high g-forces."},
    {condition: "china", value: "This circuit has fast straights, drivers must keep pace."},
    {condition: "china", value: "Acceleration out of difficult corners will be important here."},
    {condition: "china", value: "Teams will want some moderate downforce in Shanghai."},
    {condition: "china", value: "This is not an easy circuit to drive."},
    {condition: "china", value: "Drivers will want to study this circuit carefully."},
    {condition: "china", value: "There is some space for drivers to push on here."},

    {condition: "azerbaijan", value: "This street circuit is really demanding on drivers."},
    {condition: "azerbaijan", value: "Drivers are going to have a tough time here."},
    {condition: "azerbaijan", value: "Baku City is a relatively fast circuit."},
    {condition: "azerbaijan", value: "Teams will want to maintain a more balanced approach at Baku City."},
    {condition: "azerbaijan", value: "Drivers will need to focus and push on to succeed."},
    {condition: "azerbaijan", value: "Driver focus and attitude will be rewarded."},
    {condition: "azerbaijan", value: "Azerbaijan presents a difficult street circuit."},

    {condition: "spain", value: "Drivers know this circuit very well and should feel confident."},
    {condition: "spain", value: "This circuit is used for testing, and should feel familair."},
    {condition: "spain", value: "A balanced approach is helpful here."},
    {condition: "spain", value: "Teams will want to maintain speed in Spain."},
    {condition: "spain", value: "Downforce will present less of a challenge here."},
    {condition: "spain", value: "Drivers should look to be aggressive out there."},

    {condition: "monaco", value: "Monaco is well known as a difficult city circuit."},
    {condition: "monaco", value: "Downforce is in high demand at Monaco."},
    {condition: "monaco", value: "Drivers will need to give their full attention to this circuit."},
    {condition: "monaco", value: "Teams should be careful not to run too fast here."},
    {condition: "monaco", value: "This circuit is tough on drivers, staying power is vital."},
    {condition: "monaco", value: "Drivers will need to dig deep to make it in Monaco."},
    {condition: "monaco", value: "Endurance is key."},

    {condition: "canada", value: "A stop-start circuit, speed and acceleration are a focus."},
    {condition: "canada", value: "Difficult corners are the order of the day."},
    {condition: "canada", value: "Driver endurance will be tested today."},
    {condition: "canada", value: "Drivers will need to pay close attention to this circuit."},
    {condition: "canada", value: "Staying power is more important than guts."},
    {condition: "canada", value: "A fast circuit, but high demands on making those corners."},
    {condition: "canada", value: "Downforce may not the biggest factor here."},
    {condition: "canada", value: "Some acceleration out of those corners will pay dividends."},

    {condition: "france", value: "Teams will want to keep up the tempo."},
    {condition: "france", value: "Pace is vital here."},
    {condition: "france", value: "Driver endurance will be paramount in France."},
    {condition: "france", value: "This circuit is all-around demanding on driver skill."},
    {condition: "france", value: "Picking up speed out of corners will make for better times."},

    {condition: "austria", value: "A smaller circuit, but a very fast one."},
    {condition: "austria", value: "Speed is king in Austria."},
    {condition: "austria", value: "At such breakneck speeds, drivers must keep their heads."},
    {condition: "austria", value: "Drivers will need to go all out to pull ahead."},
    {condition: "austria", value: "Cornering well is also vital for maintaining speed."},

    {condition: "britain", value: "Teams should expect Silverstone to be a very high speed event."},
    {condition: "britain", value: "Picking up speed is nearly as important as maintaining it."},
    {condition: "britain", value: "Downforce may be less of a concern at Silverstone."},
    {condition: "britain", value: "Drivers will see all their skills tested to the extreme."},
    {condition: "britain", value: "Drivers will want to be especially focused out there today."},

    {condition: "hungary", value: "Teams will want to tune for downforce here."},
    {condition: "hungary", value: "There aren't many straights at the Hungaroring."},
    {condition: "hungary", value: "Downforce is the order of the day."},
    {condition: "hungary", value: "This is an exhausting circuit, that's for sure."},
    {condition: "hungary", value: "Driver training will pay off today."},
    {condition: "hungary", value: "Drivers will need to pay close attention."},

    {condition: "belgium", value: "The Belgians do like a fast race."},
    {condition: "belgium", value: "This is a very demanding circuit all-round."},
    {condition: "belgium", value: "Drivers will have all their skills tested today."},
    {condition: "belgium", value: "Driver focus will pay off here."},
    {condition: "belgium", value: "Making the straights is key."},
    {condition: "belgium", value: "Despite such high speeds, difficult corners abound."},
    {condition: "belgium", value: "Endurance will surely help drivers today."},
    
    {condition: "italy", value: "A classic circuit, and a fast one at that."},
    {condition: "italy", value: "Cars will need some powerful downforce to make it today."},
    {condition: "italy", value: "Breakneck speeds define Monza."},
    {condition: "italy", value: "Drivers will see their endurance tested."},
    {condition: "italy", value: "This will be a tiring one for drivers."},

    {condition: "singapore", value: "Marina Bay is certainly demanding, driver focus is key."},
    {condition: "singapore", value: "Mastering the corners at Marina Bay will pay off big time."},
    {condition: "singapore", value: "This is a difficult circuit, but not the fastest by far."},
    {condition: "singapore", value: "Drivers will need to be steadfast to make it through the day."},
    {condition: "singapore", value: "This city circuit requires a good amount of downforce."},

    {condition: "russia", value: "The Sochi Autodrom is a fast circuit."},
    {condition: "russia", value: "Mastering the straights here should be top priority."},
    {condition: "russia", value: "Pulling through those corners should make the difference."},
    {condition: "russia", value: "Driver staying power is going to be important here."},
    {condition: "russia", value: "Drivers must take advantage of the space available and push ahead."},

    {condition: "japan", value: "The Suzuka circuit is certainly not a slow course."},
    {condition: "japan", value: "Despite just one real straight, this circuit demands speed."},
    {condition: "japan", value: "This elaborate circuit demands some reasonable downforce."},
    {condition: "japan", value: "Drivers will need to really pay attention today."},
    {condition: "japan", value: "Staying power will be less important than skill here."},

    {condition: "mexico", value: "Three blazing fast straights make a focus on speed clear."},
    {condition: "mexico", value: "Speed is of the utmost importance here in Mexico City."},
    {condition: "mexico", value: "Keeping the pace out of those corners will be vital."},
    {condition: "mexico", value: "Drivers should have a good time out there today."},
    {condition: "mexico", value: "An offensive attitude will give drivers the edge."},

    {condition: "unitedstates", value: "This circuit features some surprisingly tricky corners."},
    {condition: "unitedstates", value: "Speed is something to keep in mind here."},
    {condition: "unitedstates", value: "Teams will want to focus on high RPM output."},
    {condition: "unitedstates", value: "Making those corners will really make the difference."},
    {condition: "unitedstates", value: "Two long straights feature prominently on this circuit."},
    {condition: "unitedstates", value: "Downforce should certainly not be ignored today."},
    {condition: "unitedstates", value: "This is an all-around difficult circuit for cars to handle."},
    {condition: "unitedstates", value: "Drivers will want to go on the offensive here."},
    {condition: "unitedstates", value: "Attentive driving will be rewarded."},

    {condition: "brazil", value: "Drivers will need to attack two long straights."},
    {condition: "brazil", value: "Speed will pay off on these straights."},
    {condition: "brazil", value: "Drivers will need to focus on accelerating out of these corners."},
    {condition: "brazil", value: "Dealing with these corners is also very important."},
    {condition: "brazil", value: "This is a fairly fast circuit."},
    {condition: "brazil", value: "Drivers will be rewarded for taking the initiative."},
    {condition: "brazil", value: "Drivers need to keep their heads and push on."},
    {condition: "brazil", value: "Endurance is less of a factor today."},

    {condition: "abudhabi", value: "This unique circuit rewards a skilled driver more than anything."},
    {condition: "abudhabi", value: "Difficult corners abound at Yas Marina."},
    {condition: "abudhabi", value: "Those straights are not to be ignored."},
    {condition: "abudhabi", value: "Not the fastest circuit, but those straights must be attacked."},
    {condition: "abudhabi", value: "Drivers must pay very close attention today."},
    {condition: "abudhabi", value: "Accelerating out of those corners will definitely pay off."},

    {condition: "start", value:"And they're off!"},
    {condition: "start", value:"Here we go!"},
    {condition: "start", value:"A good start!"},
    {condition: "start", value:"Away we go!"},
    {condition: "start", value:"Now's the time to fight for position as they round the first corner."},
    {condition: "start", value:"Going into turn one."},
    
    {condition: "general", value: "Nice cornering."},
    {condition: "general", value: "No quarter given on that turn."},
    {condition: "general", value: "Downforce and grip are absolutely vital here."},
    {condition: "general", value: "You've got to find the apex there."},
    {condition: "general", value: "Time to make a move."},
    {condition: "general", value: "A good top speed is key when approaching a straight."},
    {condition: "general", value: "Here they come bolting down the straight."},
    {condition: "general", value: "Down the straight."},
    {condition: "general", value: "Now's the time for full throttle."},
    
    {condition: "end", value: "Final corner coming up."},
    {condition: "end", value: "It's now or never."},
    {condition: "end", value: "Brilliant driving!"},
    {condition: "end", value: "Hard fought and well earned."}
]

export function sampleChatter(type) {
    type = type.toLowerCase();

    let matched = chatter.filter(x => x.condition === type)
    let rand = Math.floor(Math.random() * matched.length);
    return matched[rand].value;

}